resnet50:
  parameters:
    adam_lr: 0.001
    epochs: 100
    loss: euclidean
    metrics: ['mse']
    es_patience: 5
    monitor: val_mse
    es_min_delta: 0.001

vgg16:
  parameters:
    adam_lr: 0.0001
    epochs: 100
    loss: mse
    metrics: ['mae']
    es_patience: 5
    monitor: val_mae
    es_min_delta: 0.001

vgg19:
  parameters:
    adam_lr: 0.0001
    epochs: 100
    loss: euclidean
    metrics: ['mse']
    es_patience: 5
    monitor: val_mse
    es_min_delta: 0.001

xception:
  parameters:
    adam_lr: 0.001
    epochs: 100
    loss: mse
    metrics: ['mae']
    es_patience: 3
    monitor: val_mae
    es_min_delta: 0.001

csrnet:
  parameters:
    adam_lr: 0.0001
    epochs: 50
    loss: mse
    metrics: ['mae']
    es_patience: 10
    monitor: val_mae
    es_min_delta: 0.001
